<?php

namespace App\HttpController\Api\User;


use App\HttpController\Api\ApiBase;

class Register extends ApiBase
{
    public function index()
    {
        
        parent::index(); // TODO: Change the autogenerated stub
    }
}